spring:
  application:
    name: price-monitoring-servie

  jpa:
      hibernate:
        ddl-auto: update

  datasource:
      url: jdbc:mysql://localhost:3306/amazon_price_monitoring_db?verifyServerCertificate=false&useSSL=false&requireSSL=false
      username: username
      password: password
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 9000

