server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: eureka
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:${vcap.services.${PREFIX:}configserver.credentials.uri:http://localhost:8888}}