server:
  port: 8080

spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/amazon_price_monitoring_db?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

