spring:
  application:
    name: email-notification-service

  jpa:
      hibernate:
        ddl-auto: update

  datasource:
      url: jdbc:mysql://localhost:3306/amazon_price_monitoring_db?verifyServerCertificate=false&useSSL=false&requireSSL=false
      username: username
      password: password
      driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

server:
  port: 9001

